INSERT INTO languages_and_regions VALUES
    (1,'arb','Arabic','Arabic','عربي'),
    (2,'cn-ma','Chinese','Chinese, Mandarin','中國普通話'),
    (3,'cn-ca','Chinese','Chinese, Cantonese','廣東話'),
    (4,'da','Danish','Danish','Dansk'),
    (5,'nl','Dutch','Dutch','Nederlands'),
    (6,'en-au','English','English, Australia','English'),
    (7,'en-gb','English','English, Great Britain','English'),
    (8,'en-in','English','English, India','English'),
    (9,'en-us','English','English, US','English'),
    (10,'fr-fr','French','French, France','Français'),
    (11,'fr-ca','French','French, Canada','Français'),
    (12,'de-de','German','German, Germany','Deutsch'),
    (13,'de-ch','German','German, Switzerland','Schwiizerdütsch'),
    (14,'de-at','German','German, Austria','Österreichisches Deutsch'),
    (15,'de-be','German','German, Berlin','Berlinerisch'),
    (16,'de-ba','German','German, Bavarian','Bayerisch'),
    (17,'ko','Korean','Korean','Korean'),
    (18,'no','Norwegian','Norwegian','Norwegian'),
    (19,'pl','Polish','Polish','Polskie'),
    (20,'pt-pt','Portuguese','Portuguese, Portugal','Português'),
    (21,'pt-br','Portuguese','Portuguese, Brazil','Português'),
    (22,'ro','Romanian','Romanian','Română'),
    (23,'ru','Russian','Russian','русский'),
    (24,'es-can','Spanish','Spanish, Canary Islands','Español'),
    (25,'es-car','Spanish','Spanish, Caribbean Islands','Español'),
    (26,'es-es','Spanish','Spanish, Castilian','Castellano'),
    (27,'es-mx','Spanish','Spanish, Mexico','Español'),
    (28,'es-rio','Spanish','Spanish, Rioplatense','Español'),
    (29,'es-us','Spanish','Spanish, US','Español'),
    (30,'sv','Swedish','Swedish','Swedish'),
    (31,'tr','Turkish','Turkish','Türk'),
    (32,'vn-nor','Vietnamese','Vietnamese, North','Tiếng Việt'),
    (33,'vn-sou','Vietnamese','Vietnamese, South','Tiếng Việt'),
    (34,'vn-cen','Vietnamese','Vietnamese, Central','Tiếng Việt'),
    (35,'cy','Welsh','Welsh','Cymraeg'),
    (36,'in-ben','Bengali','Bengali','Bengali'),
    (37,'in-mar','Marathi','Marathi','Marathi'),
    (38,'in-tel','Telugu','Telugu','Telugu'),
    (39,'in-tam','Tamil','Tamil','Tamil'),
    (40,'in-urd','Urdu','Urdu','Urdu'),
    (41,'in-guj','Gujarati','Gujarati','Gujarati'),
    (42,'in-kan','Kannada','Kannada','Kannada'),
    (43,'in-may','Malayalam','Malayalam','Malayalam'),
    (44,'in-odi','Odia','Odia','Odia'),
    (45,'in-pun','Punjabi','Punjabi','Punjabi'),
    (46,'in-asm','Assamese','Assamese','Assamese'),
    (47,'in-mai','Maithili','Maithili','Maithili'),
    (48,'in','Hindi','Hindi','Hindi'),
    (49,'jp','Japanese','Japanese','日本'),
    (50,'is','Icelandic','Icelandic','Íslenskur'),
    (51,'it','Italian','Italian','Italiano'),
    (52,'es-ca','Catalan','Catalan','Catàleg'),
    (53,'en','English','English',NULL),
    (54,'es','Spanish','Spanish',NULL),
    (55,'fr','French','French',NULL);


INSERT INTO user_language_mapping(id,user_id,language_id) VALUES (9,4,48);
INSERT INTO user_language_mapping(id,user_id,language_id) VALUES (10,4,49);
INSERT INTO user_language_mapping(id,user_id,language_id) VALUES (11,4,50);

