const BookData = {
  languages: {
    author: "Dale Neal",
    illustrator: "Liumin Zhang",
    composer: "Artyom Akmulin",
    publisher: "Diveo Media",
    size: {
      desktop: {
        default: {
          width: 1280,
          height: 720
        }
      }
    },
    effects: {
      1: `diveo_media/a_guest_on_a_farm/zip/1.zip`,
      2: `diveo_media/a_guest_on_a_farm/zip/2.zip`,
      3: `diveo_media/a_guest_on_a_farm/zip/3.zip`,
      4: `diveo_media/a_guest_on_a_farm/zip/4.zip`,
      5: `diveo_media/a_guest_on_a_farm/zip/5.zip`,
      6: `diveo_media/a_guest_on_a_farm/zip/6.zip`,
      7: `diveo_media/a_guest_on_a_farm/zip/7.zip`,
      8: `diveo_media/a_guest_on_a_farm/zip/8.zip`,
      9: `diveo_media/a_guest_on_a_farm/zip/9.zip`,
      10: `diveo_media/a_guest_on_a_farm/zip/10.zip`,
      11: `diveo_media/a_guest_on_a_farm/zip/11.zip`,
      12: `diveo_media/a_guest_on_a_farm/zip/12.zip`,
      13: `diveo_media/a_guest_on_a_farm/zip/13.zip`,
      14: `diveo_media/a_guest_on_a_farm/zip/14.zip`,
      15: `diveo_media/a_guest_on_a_farm/zip/15.zip`,
      16: `diveo_media/a_guest_on_a_farm/zip/16.zip`,
      17: `diveo_media/a_guest_on_a_farm/zip/17.zip`,
      18: `diveo_media/a_guest_on_a_farm/zip/18.zip`,
      19: `diveo_media/a_guest_on_a_farm/zip/19.zip`,
      20: `diveo_media/a_guest_on_a_farm/zip/20.zip`,
      21: `diveo_media/a_guest_on_a_farm/zip/21.zip`,
      22: `diveo_media/a_guest_on_a_farm/zip/22.zip`,
      23: `diveo_media/a_guest_on_a_farm/zip/23.zip`,
      24: `diveo_media/a_guest_on_a_farm/zip/24.zip`,
      25: `diveo_media/a_guest_on_a_farm/zip/25.zip`,
      26: `diveo_media/a_guest_on_a_farm/zip/26.zip`,
      27: `diveo_media/a_guest_on_a_farm/zip/27.zip`,
      28: `diveo_media/a_guest_on_a_farm/zip/28.zip`,
      29: `diveo_media/a_guest_on_a_farm/zip/29.zip`,
      30: `diveo_media/a_guest_on_a_farm/zip/30.zip`,
      31: `diveo_media/a_guest_on_a_farm/zip/31.zip`,
      32: `diveo_media/a_guest_on_a_farm/zip/32.zip`,
      33: `diveo_media/a_guest_on_a_farm/zip/33.zip`,
      34: `diveo_media/a_guest_on_a_farm/zip/34.zip`,
      35: `diveo_media/a_guest_on_a_farm/zip/35.zip`,
      36: `diveo_media/a_guest_on_a_farm/zip/36.zip`,
      37: `diveo_media/a_guest_on_a_farm/zip/37.zip`,
      38: `diveo_media/a_guest_on_a_farm/zip/38.zip`,
      39: `diveo_media/a_guest_on_a_farm/zip/39.zip`,
      40: `diveo_media/a_guest_on_a_farm/zip/40.zip`,
      41: `diveo_media/a_guest_on_a_farm/zip/41.zip`,
      42: `diveo_media/a_guest_on_a_farm/zip/42.zip`,
      43: `diveo_media/a_guest_on_a_farm/zip/43.zip`,
      44: `diveo_media/a_guest_on_a_farm/zip/44.zip`,
      45: `diveo_media/a_guest_on_a_farm/zip/45.zip`,
      46: `diveo_media/a_guest_on_a_farm/zip/46.zip`
    },
    languages: {
      en: {
        title: "A Guest on the Farm",
        description:
          "What do a towering giraffe and a little farmer have to teach one another? And how will they help each other learn about the joys of sharing? Find out in this tale of farmyard friendship.",
        content: {
          1: "There once was a beautiful young girl named Marie, who lived and worked on a busy little fruit farm, deep in the countryside.",
          2: "Every morning she would wake early, hop aboard her bright red tractor and ride around the farm.",
          3: "She climbed her trusty old ladder and picked the fruit from the trees to sell at the local market.",
          4: "But try as she might, Marie could never pick the tastiest, sweetest fruit from the highest branches...",
          5: "Even from the very top of her ladder, she just couldn’t reach. Yet she still hoped to one day gather that tasty fruit.",
          6: "Every evening when her work was done, she would sit alone on the warm hillside...",
          7: "Eating the sweet, fresh fruit while watching the summer sun set peacefully over the meadows.",
          8: "One day, quite unexpectedly, a lone giraffe came galloping through the farm.",
          9: 'He was by far the tallest animal Marie had ever seen, taller than an acorn tree..: "and extremely frightened!',
          10: '“What’s the matter, my mighty friend?" asked Marie. "How can I help?"',
          11: "The giraffe cried, “I was being chased by hunters, and now I’m lost and alone. I’m so tired and hungry, and I have nowhere to go.”",
          12: "“That’s so sad,” said Marie. “Why don’t you stay with me? You’ll be safe, and you can eat all the fresh leaves you like.”",
          13: "“Oh, thank you so much!” exclaimed the giraffe. “That is so kind of you. I promise I’ll be no trouble at all.”",
          14: "Over time, Marie and the giraffe became the very best of friends.",
          15: "When she wasn’t working on the farm, they would laugh and play together in the warm summer sunshine.",
          16: "Every evening they would sit together on the hillside. The giraffe would munch on his leaves, Marie would eat the sweet fruit...",
          17: "And together they would watch the summer sun set peacefully over the meadows.",
          18: "One warm, sunny afternoon, the giraffe was taking a walk through the fruit trees...",
          19: "When he happened upon the barn where the fruit was stored for market.",
          20: "The giraffe slowly and carefully pushed his long neck through the open window and peered inside.",
          21: "There he saw barrels, baskets and carts filled to the brim with juicy, ripe fruit.",
          22: "The giraffe could not resist. The fruit looked so tasty and sweet, and he was bored of eating nothing but leaves all the time.",
          23: "He squeezed his enormous body inside...",
          24: "And started eating the sweet fruit. It was delicious!",
          25: "The hungry giraffe ate and ate, until his belly was fit to burst, and the barrels, baskets and carts were empty.",
          26: "His face turned a bright shade of green and he began to feel extremely unwell.",
          27: "Later that afternoon, Marie was enjoying a peaceful stroll through the farm, hoping to find her friend.",
          28: "Suddenly she heard a pained groaning sound coming from the barn.",
          29: "She burst into the barn to see what had happened...",
          30: "And was surprised to find the giraffe sitting forlornly among the empty carts, barrels and baskets... surrounded by peels and seeds.",
          31: "Marie was shocked and saddened to see that her friend had eaten all the fruit, and there was now none left to sell at the market.",
          32: "“I’m so sorry!” said the giraffe. “I just wanted to taste the fruit... but it was so tasty that I kept eating. Now I feel unwell.”",
          33: "“Fruit is tasty,” agreed Marie. “And it’s good for you. But eating too much can make anyone feel unwell.”",
          34: "“But don’t worry, you’ll soon feel better,” she added reassuringly.",
          35: "“But now I’ve eaten all the fruit, how can you go to market?” asked the giraffe, feeling extremely guilty and rather silly.",
          36: "“I have an idea!” replied Marie...",
          37: "“With your long neck, you can easily pick the sweetest, tastiest fruit from the highest branches where no one else can reach.”",
          38: "“Would you like to help me on the farm?” she asked.",
          39: "“It would be my pleasure!” replied the giraffe.",
          40: 'So from that day forward, Marie and the giraffe worked happily together on the farm. 41: "They rode around in their bright red tractor, gathering the fruit in the sunshine.',
          42: "They picked only the sweetest, juiciest, most delicious fruit from the very highest branches, where only the mighty giraffe could reach.",
          43: "People would travel from miles around to buy the fruit. Everyone agreed it was by far the sweetest and juiciest fruit in all the land.",
          44: "Every evening after working on the farm, Marie and her friend the giraffe would sit together on the warm hillside...",
          45: "Eating the sweet, tasty fruit while watching the sun set peacefully over the meadows...",
          46: "...and the fruit tasted so much sweeter when it was shared."
        }
      },
      fr: {
        title: "A Guest on the Farm",
        description:
          "What do a towering giraffe and a little farmer have to teach one another? And how will they help each other learn about the joys of sharing? Find out in this tale of farmyard friendship.",
        content: {
          1: "There once was a beautiful young girl named Marie, who lived and worked on a busy little fruit farm, deep in the countryside.",
          2: "Every morning she would wake early, hop aboard her bright red tractor and ride around the farm.",
          3: "She climbed her trusty old ladder and picked the fruit from the trees to sell at the local market.",
          4: "But try as she might, Marie could never pick the tastiest, sweetest fruit from the highest branches...",
          5: "Even from the very top of her ladder, she just couldn’t reach. Yet she still hoped to one day gather that tasty fruit.",
          6: "Every evening when her work was done, she would sit alone on the warm hillside...",
          7: "Eating the sweet, fresh fruit while watching the summer sun set peacefully over the meadows.",
          8: "One day, quite unexpectedly, a lone giraffe came galloping through the farm.",
          9: 'He was by far the tallest animal Marie had ever seen, taller than an acorn tree..: "and extremely frightened!',
          10: '“What’s the matter, my mighty friend?" asked Marie. "How can I help?"',
          11: "The giraffe cried, “I was being chased by hunters, and now I’m lost and alone. I’m so tired and hungry, and I have nowhere to go.”",
          12: "“That’s so sad,” said Marie. “Why don’t you stay with me? You’ll be safe, and you can eat all the fresh leaves you like.”",
          13: "“Oh, thank you so much!” exclaimed the giraffe. “That is so kind of you. I promise I’ll be no trouble at all.”",
          14: "Over time, Marie and the giraffe became the very best of friends.",
          15: "When she wasn’t working on the farm, they would laugh and play together in the warm summer sunshine.",
          16: "Every evening they would sit together on the hillside. The giraffe would munch on his leaves, Marie would eat the sweet fruit...",
          17: "And together they would watch the summer sun set peacefully over the meadows.",
          18: "One warm, sunny afternoon, the giraffe was taking a walk through the fruit trees...",
          19: "When he happened upon the barn where the fruit was stored for market.",
          20: "The giraffe slowly and carefully pushed his long neck through the open window and peered inside.",
          21: "There he saw barrels, baskets and carts filled to the brim with juicy, ripe fruit.",
          22: "The giraffe could not resist. The fruit looked so tasty and sweet, and he was bored of eating nothing but leaves all the time.",
          23: "He squeezed his enormous body inside...",
          24: "And started eating the sweet fruit. It was delicious!",
          25: "The hungry giraffe ate and ate, until his belly was fit to burst, and the barrels, baskets and carts were empty.",
          26: "His face turned a bright shade of green and he began to feel extremely unwell.",
          27: "Later that afternoon, Marie was enjoying a peaceful stroll through the farm, hoping to find her friend.",
          28: "Suddenly she heard a pained groaning sound coming from the barn.",
          29: "She burst into the barn to see what had happened...",
          30: "And was surprised to find the giraffe sitting forlornly among the empty carts, barrels and baskets... surrounded by peels and seeds.",
          31: "Marie was shocked and saddened to see that her friend had eaten all the fruit, and there was now none left to sell at the market.",
          32: "“I’m so sorry!” said the giraffe. “I just wanted to taste the fruit... but it was so tasty that I kept eating. Now I feel unwell.”",
          33: "“Fruit is tasty,” agreed Marie. “And it’s good for you. But eating too much can make anyone feel unwell.”",
          34: "“But don’t worry, you’ll soon feel better,” she added reassuringly.",
          35: "“But now I’ve eaten all the fruit, how can you go to market?” asked the giraffe, feeling extremely guilty and rather silly.",
          36: "“I have an idea!” replied Marie...",
          37: "“With your long neck, you can easily pick the sweetest, tastiest fruit from the highest branches where no one else can reach.”",
          38: "“Would you like to help me on the farm?” she asked.",
          39: "“It would be my pleasure!” replied the giraffe.",
          40: 'So from that day forward, Marie and the giraffe worked happily together on the farm. 41: "They rode around in their bright red tractor, gathering the fruit in the sunshine.',
          42: "They picked only the sweetest, juiciest, most delicious fruit from the very highest branches, where only the mighty giraffe could reach.",
          43: "People would travel from miles around to buy the fruit. Everyone agreed it was by far the sweetest and juiciest fruit in all the land.",
          44: "Every evening after working on the farm, Marie and her friend the giraffe would sit together on the warm hillside...",
          45: "Eating the sweet, tasty fruit while watching the sun set peacefully over the meadows...",
          46: "...and the fruit tasted so much sweeter when it was shared."
        }
      }
    }
  }
};

export default BookData;
