const BookData = {
  author: "Altai Zeinalov",
  composer: "Artyom Akmulin",
  illustrator: "Natalia Asanova",
  publisher: "Diveo Media",
  languages: {
    en: {
      title: "True Friendship",
      description:
        "It is so good to have real friends. They share your joy and your sorrow and help you in your hour of need. Above all, everything you do is much more pleasant when you do it with your friends – especially if it is sport.",
      content: {
        1: "There are many towns situated at the foot of mountains. These towns are renowned for clean air and the love of their inhabitants for winter sports.",
        2: "A nice girl named Ilona lives in one of these towns.",
        3: "Having finished her housework, she decided to go to the river and feast her eyes on the beauties of nature.",
        4: "She enjoyed watching the wild animals, especially birds – they were so cute and funny.",
        5: "But now and again Ilona felt bored because she lacked company.",
        6: "When she looked into the distance she asked herself many questions:",
        7: '"How can I find a friend? What is there in the distance? Is it just snow?"',
        8: "While Ilona was thinking about it, someone was rushing down the hill at a great speed.",
        9: 'That "someone" was cat Leo. "Wow! This is just cool!"',
        10: "He was keen on sports, especially skiing and snowboarding.",
        11: "Although Leo had been skiing in the mountains for a long time, he felt lonely sometimes because there was no one to share his delight with.",
        12: 'However, everything was going to change that day.Leo made a decision. "I have to find a friend! And I will find one!"',
        13: "The cat slid down to the foot of the mountain where a river flowed.",
        14: "He used his snowboard as a float and swam towards the town decisively as he was eager to find a new friend.",
        15: "By that time, Ilona got tired of sitting on the quay and was about to go home,",
        16: 'When suddenly she heard a voice behind her: "Wait!"',
        17: '"Who are you?" Ilona asked in surprise.',
        18: '"My name is Leo! I have just come down from the mountain in order to find a friend. Do you want to be my friend? What is your name?"',
        19: '"My name is Ilona", the girl answered humbly. "And I am looking for a friend too."',
        20: '"Awesome!" said the cat and jumped out onto the shore joyfully.',
        21: '"Ilona, do you want me to show you the real mountains and the real fun?"',
        22: '"Maybe...What are we going to do?"',
        23: '"You\'re going to like it! Let’s go to my house and I will give you a present."',
        24: '"The new friends came to a little tree and Leo said, "Wait for me here, Ilona, I\'ll be back in a moment."',
        25: "The girl waited, completely unaware of what the cat was going to bring her.",
        26: '"Here you are, Ilona! These are your new skis. Let’s go up the hill and I’ll show you that skiing is an awesome activity!"',
        27: '"Thank you so much, Leo! I didn\'t expect such a nice present from you."',
        28: "They climbed up the hill. The cat explained to Ilona how to keep balance while skiing.",
        29: '"And now, Ilona, it’s time for us to slide downhill. Follow me!"',
        30: "The girl watched the cat sliding down the slope on his skis.",
        31: "She didn’t want to stay in the mountains alone for a long time so she mustered up the nerve and took the first step...",
        32: "Zing! Ilona is sliding! Look how happy she is. Well done, Ilona!",
        33: "And Leo has done such a great job! He taught the girl how to ski.",
        34: "So this is the way the cat and the girl became the best friends.",
        35: "Later on, Ilona taught Leo how to ride a bicycle. True friendship manifests itself through little things like this."
      }
    },
    fr: {
      title: "Une histoire d’amitié",
      description:
        "C’est si bon d’avoir des amis. Ils partagent ta joie et ta tristesse et sont là quand tu as besoin d’eux. Et tout est plus plaisant quand tu le fais avec des amis, surtout s’il s’agit de sport.",
      content: {
        1: "Les villes situées au pied des montagnes sont souvent célèbres pour leur air pur et l’amour de leurs habitants pour le ski.",
        2: "Dans une de ces petites villes habitait une jolie fillette appelée Nicole.",
        3: "Ayant terminé ses tâches ménagères, elle décida d'aller à la rivière pour profiter de la beauté de la nature.",
        4: "Elle aimait observer les animaux, surtout les oiseaux, ces petites créatures ravissantes et si drôles.",
        5: "Pourtant, parfois Nicole s'ennuyait et se sentait seule.",
        6: "Lorsqu'elle regardait au loin, elle se posait de nombreuses questions:",
        7: '"Où puis-je trouver un ami ? Qu\'y a-t-il tout là-haut? Uniquement de la neige?"',
        8: "Pendant que Nicole pensait aux montagnes enneigées, quelqu'un les parcourait à vive allure.",
        9: 'Ce quelqu’un était Basile le chat. Il dévalait les pentes en criant: "C\'est génial!"',
        10: "Il adorait le sport, surtout le ski et le surf de neiges.",
        11: "Bien qu'il ait toujours su skier dans ces montagnes, il était souvent triste parce qu'il n'y avait personne avec qui partager ce plaisir.",
        12: "Mais ce jour-là, tout allait changer.Basile en était sûr et il dit: \"J'ai besoin d'un ami et je le trouverais!\"",
        13: "Le chat dévala la pente jusqu’au pied de la montagne jusqu’à tomber sur une rivière.",
        14: "Utilisant sa planche de surf comme une bouée, Basile nagea, rempli d’espoir, en direction de la ville, à la recherche d’un ami.",
        15: "Pendant ce temps, Nicole, fatiguée de rester au bord de la rivière, se préparait à rentrer chez elle.",
        16: 'Quand tout à coup, elle entendit une voix derrière elle: "Attends une seconde, fillette!"',
        17: 'Surprise, la petite fille lui demanda: "Mais qui es-tu?"',
        18: '"Je m\'appelle Basile! Je suis descendu des montagnes pour trouver un ami. Veux-tu être mon amie? Comment t’appelles-tu?"',
        19: '"Je m’appelle Nicole," répondit timidement la petite fille. "Et, moi aussi, je cherche un ami."',
        20: '"Mais c’est parfait alors!", s\'exclama le chat en regagnant joyeusement la rive.',
        21: '"Nicole, veux-tu que je te fasse découvrir les vraies montagnes et le vrai bonheur?"',
        22: '"Euh, peut-être!" répondit-elle. "Que veux-tu faire?"',
        23: '"Je suis sûr que tu vas aimer! Rendons-nous chez moi, j’ai quelque chose pour toi."',
        24: 'Les amis arrivèrent ensemble jusqu’à un petit arbre et Basile lui dit : "Attends-moi ici, je reviens tout de suite."',
        25: "La fillette attendit patiemment, se demandant bien ce qu’il allait rapporter.",
        26: '"Tiens, Nicole ! Voilà tes nouveaux ski. Montons maintenant et tu découvriras que ce sport est génial!"',
        27: '"Merci beaucoup, Basile! Je ne m’attendais pas à un tel cadeau."',
        28: "Ils grimpèrent ensemble et, arrivés en haut, le chat expliqua à la fillette comment garder l'équilibre.",
        29: '"Et maintenant, il est temps de descendre. Suis-moi!"',
        30: "La fillette observa le chat descendre adroitement sur son surf.",
        31: "Mais ne voulant pas rester seule en haut de la montagne, elle prit son courage à deux mains et se lança à son tour.",
        32: "Quelle sensation! Quel bonheur! Nicole glissa sur la pente. Bravo Nicole!",
        33: "Tout cela grâce à Basile qui a appris à la fillette à faire du ski.",
        34: "C'est ainsi que le chat et Nicole devinrent les meilleurs amis du monde.",
        35: "Nicole à son tour apprit à Basile à faire du vélo.Les véritables amitiés se manifestent dans ces petits gestes."
      }
    },
    de: {
      title: "Wahre Freundschaft",
      description:
        "Freunde fürs Leben zu haben, ist großartig. Sie teilen Freud und Leid und helfen in der Not. Aber Hauptsache ist, dass mit ihnen jede Beschäftigung ein großer Spaß ist, insbesondere wenn es um Sport geht.",
      content: {
        1: "Städte am Fuße des Gebirges sind immer bekannt für ihre saubere Luft und die Liebe der Bewohner zum Skisport.",
        2: "In einem solchen Städtchen lebt das sympathische Mädchen Ilona.",
        3: "Nach der Hausarbeit beschloss sie, zum Bach zu gehen und die Schönheiten der Natur zu bewundern.",
        4: "Sie beobachtet gerne Tiere, besonders Vögel, so possierliche und niedliche Geschöpfe.",
        5: "Nur hin und wieder war Ilona langweilig, weil ihr Gesellschaft fehlte.",
        6: "Als sie in die Ferne blickte, fragte sie sich:",
        7: "„Wo bloß finde ich einen Freund? Was ist dort in der Ferne? Wohl nur Schnee?“",
        8: "Während Ilona ihren Gedanken nachhing, durchpflügte jemand mit großer Geschwindigkeit die Weiten der schneebedeckten Gipfel.",
        9: "Dieser Jemand war Kater Tizian: „Ja- a - a! Wie toll!“",
        10: "Er liebte Sport, aber am besten gefielen ihm Skier und Snowboards.",
        11: "Obwohl Tizian schon lange in diesen Bergen lebte, war er oft schwermütig, weil er diese Freude mit niemandem teilen konnte.",
        12: "Aber heute änderte sich alles. Tizian erkläret bestimmt: „Ich muss einen Freund finden! Und heute finde ich ihn!“",
        13: "Der Kater fuhr zum Bergfuß ab, dorthin, wo der Bach floss, um sich auf ihm schwimmend in die Stadt zu begeben.",
        14: "Tizian verwendete das Snowboard als Floß und schwamm sicher in Richtung des Städtchens, um seinen neuen Freund zu suchen.",
        15: "Zur gleichen Zeit war es Ilona bereits überdrüssig, an der Anlegestelle zu sitzen, und sie machte sich auf den Heimweg.",
        16: "Doch plötzlich hörte sie von hinten eine Stimme: „Bleib stehen, Mädchen!“",
        17: "Die erstaunte Ilona fragte: „Oh, wer bist du denn?”",
        18: "„Ich bin Tizian! Ich bin vom Gebirge heruntergekommen, um einen Freund zu finden. Wollen wir Freunde sein? Wie heißt du?“",
        19: "„Ich heiße Ilona“, antwortete das Mädchen schüchtern. „Und ich suche auch einen Freund...“",
        20: "„Ausgezeichnet!“, rief der Kater und sprang erfreut ans Ufer.",
        21: "„Ilona, möchtest du, dass ich dir die Berge und ein echtes Vergnügen zeige?“",
        22: "„Gewiss... Und was machen wir?“",
        23: "„Oh, dir wird es gefallen! Gehen wir zu mir nach Hause, ich schenke dir etwas.“",
        24: "Die Freunde gingen zu einem kleinen Baum. Tizian sagte: „Ilona, ich komme gleich nach, warte ein wenig auf mich.“",
        25: "Zwei Minuten lang ließ der Kater das Mädchen völlig im Unklaren. Was wollte er bringen?",
        26: "„Hier, Ilona! Das sind deine neuen Skier. Wir steigen nun ins Gebirge auf und du wirst sehen, dass Sport etwas Tolles ist!“",
        27: "„Vielen Dank, Tizian! Ich habe so ein Geschenk nicht erwartet.“ 28. Nachdem sie auf einen kleinen Berg gestiegen waren, erklärte der Kater dem Mädchen, wie man richtig das Gleichgewicht hielt.",
        29: "„Also, Ilona, es ist nun an der Zeit, dass du den Berg hinunterfährst. Mach es mir nach!“",
        30: "Das Mädchen beobachtete, wie der Kater auf dem Snowboard geschickt abfuhr.",
        31: "Sie wollte nicht lange allein im Gebirge bleiben. Sie nahm ihren Mut zusammen und entschloss sich, den ersten Schritt zu tun...",
        32: "Schwupp! Ilona rauschte davon! Wie viel Freude sie hatte.Großartig, Ilona!",
        33: "Und wie gut Tizian war! Er hatte dem Mädchen das Skifahren beigebracht.",
        34: "So schlossen der Kater und Ilona Freundschaft und wurden die besten Freunde.",
        35: "Danach zeigte Ilona Tizian, wie man Rad fuhr. In solchen Kleinigkeiten äußert sich wahre Freundschaft."
      }
    },
    ru: {
      title: "Веселее вместе",
      description:
        "Иметь друзей по жизни – это здорово. Они разделяют с тобой радость и грусть, помогают в трудную минуту. Но главное, что с ними любое занятие приносит больше удовольствия – особенно, если это спорт.",
      content: {
        1: "Города у подножья гор всегда славятся своим чистым воздухом и любовью жителей к горнолыжному спорту.",
        2: "В одном из таких городков живёт симпатичная девочка Илона.",
        3: "После домашней уборки она решила отправиться к речке, полюбоваться красотами природы.",
        4: "Ей нравилось наблюдать за животными, особенно за птичками – такие забавные и милые создания.",
        5: "Только временами Илоне становилось скучно, потому что ей не хватало общения.",
        6: "Когда она смотрела вдаль, то задавалась вопросами:",
        7: "«Где же мне найти друга? Что же там вдалеке? Неужели просто снег?»",
        8: "Пока Илона размышляла, кто-то на больших скоростях бороздил просторы снежных вершин.",
        9: "И этим кто-то был кот Васька: «Да-а-а! Как здорово!»",
        10: "Он обожает спорт, но больше всего любит лыжи и сноуборд.",
        11: "Хоть Васька и давно катается в этих горах, нередко ему бывает тоскливо, потому что разделить эту радость не с кем.",
        12: "Но сегодня всё изменится. Васька уверенно заявил: «Мне нужно найти друга! И я его найду!»",
        13: "Котик спустился к подножью горы, туда, где текла река, чтобы отправиться вплавь по ней в город.",
        14: "Васька использовал сноуборд как плот и уверенно поплыл в сторону городка – искать своего нового друга.",
        15: "В это время Илоне уже надоело сидеть на пристани, и она собралась домой.",
        16: "Но вдруг послышался голос из- за спины: «Постой, девочка!»",
        17: "Удивлённая Илона спросила: «Ой, а ты кто?»",
        18: "«Я Васька! Спустился с гор, чтобы найти друга. Давай дружить? Как тебя зовут?»",
        19: "«Я Илона, – робко ответила девочка, – и... я тоже ищу друга...»",
        20: "«Отлично!» – воскликнул кот и радостно выпрыгнул на берег.",
        21: "«Илона, а хочешь, я покажу тебе горы и настоящее веселье?»",
        22: "«Наверное... А что мы будем делать?»",
        23: "«О, тебе понравится! Пойдём к моему дому, я тебе кое-что подарю».",
        24: "Друзья подошли к небольшому деревцу, и Васька сказал: «Илона, я сейчас, подожди меня немного».",
        25: "На две минутки кот оставил девочку в полном неведении. Что он собирается принести?",
        26: "«Держи, Илона! Это твои новые лыжи. Сейчас мы поднимемся в горы, и ты поймёшь, что спорт – это очень здорово!»",
        27: "«Большое спасибо, Васька! Я не ожидала такого подарка».",
        28: "Забравшись на небольшую вершину, котик объяснил девочке, как правильно держать равновесие.",
        29: "«Ну что ж, Илона, пора тебе скатиться с горки. Повторяй за мной!»",
        30: "Девочка наблюдала за тем, как кот ловко спускается с горы на сноуборде. 31. Ей не хотелось долго оставаться одной в горах. Она набралась смелости и решила сделать первый шаг...",
        32: "Вжих! Поехала Илона! Сколько же в ней радости. Умница, Илона!",
        33: "А Васька какой молодец! Научил девочку кататься.",
        34: "Вот так и подружились кот и Илона, так и стали лучшими друзьями.",
        35: "А потом Илона показала Ваське, как кататься на велосипеде. Вот в таких мелочах и проявляется настоящая дружба."
      }
    }
  }
};

export default BookData;
